# Generated by Django 3.2.3 on 2021-11-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del usuario')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='nombre del usuario')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo del usuario')),
                ('password', models.CharField(max_length=50, verbose_name='contraseña del usuario')),
            ],
        ),
    ]
